### ISSUE TITLE
Helpful tip when using a sink type of cassandra-sink

### ISSUE THREAD

**Issue by ddieruf** [LangStream/documentation#33]
The value of the secure connect bundle comes from the command:
`base64 ./secure-connect-asdf.zip > ./b64-secure-connect.txt`

It's going to be 100's of lines of text so to add it in the secrets manifest:

```yaml
secrets:
  - name: cassandra
    id: cassandra
   data:
      username: <something>
      password: <something>
      secure-connect-bundle: |
        UEsDBBQACAAIAIumC1cAAAAAAAAAAAAAAAAGAAkAY2EuY3J0VVQFAAGHn9ZkZJTNkro4FMX3PMXs
        rSkBP5DFf3EDIYAGDfIVd4IaxAYVa.......
```
