### ISSUE TITLE
text-normaliser has incorrect values

### ISSUE THREAD

**Issue by ddieruf** [LangStream/documentation#8]
Example of correct values
```
- name: "Normalise text"
    type: "text-normaliser"
    configuration:
      make-lowercase: true
      trim-spaces: true
```
