### ISSUE TITLE
text-splitter has incorrect values

### ISSUE THREAD

**Issue by ddieruf** [LangStream/documentation#9]
Correct example
```
- name: "Split into chunks"
    type: "text-splitter"
    configuration:
      splitter_type: "RecursiveCharacterTextSplitter"
      chunk_size: 400
      separators: ["\n\n", "\n", " ", ""]
      keep_separator: false
      chunk_overlap: 100
      length_function: "cl100k_base"
```
